# Site settings
title: Zach Waterson's Musings
# email: zachwaterson@mac.com
description: > # this means to ignore newlines until "baseurl:"
  The place where I wax poetic about Christopher Nolan, Apple, and life in general.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://zachwaterson.com" # the base hostname & protocol for your site
twitter_username: H2Oson_
github_username:  zachwaterson

# Build settings
markdown: kramdown
